core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('padaria.urls', namespace='padaria')),
    path('admin/', admin.site.urls),
]

padaria/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import ListView

from core import settings
from padaria.views import home, cria_cliente, cria_produto, lista_clientes, lista_produtos, detalhe_produto, \
    atualiza_produto, RemoveProdutoView, VendaListView, VendaCreateView, AtualizaCreateView, RemoveVendaView

app_name = 'padaria'

urlpatterns = [
    path('', home),
    path('produtos/', lista_produtos, name='lista_produtos'),
    path('produtos/parametro_invalido', cria_produto),
    path('produtos/detalhe/<pk>', detalhe_produto),
    path('produtos/atualiza/<pk>', atualiza_produto, name='produtos_atualiza'),
    path('clientes/', lista_clientes),
    path('clientes/novo', cria_cliente),
    path('produtos/novoProduto', cria_produto),
    path('produtos/remove/<pk>', RemoveProdutoView.as_view(), name='remove_produto'),

    #Vendas
    path('vendas/', VendaListView.as_view(), name='lista_vendas'),
    path('vendas/novo', VendaCreateView.as_view(), name='nova_venda'),
    path('vendas/atualiza/<pk>', AtualizaCreateView.as_view(), name='atualiza_venda'),
    path('vendas/remove/<pk>', RemoveVendaView.as_view(), name='remove_venda'),

    # #Fila
    # path('fila/', FilaListView.as_view(), name='lista_fila'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

padaria/models.py
from django.db import models


# Create your models here.
class Cliente(models.Model):
    nome = models.CharField(
        max_length=30,
        null=False,
        blank=False
    )
    sobrenome = models.CharField(
        max_length=50,
        null=False,
        blank=False
    )
    cpf = models.CharField(
        max_length=14,
        null=False,
        blank=False
    )
    email = models.EmailField(
        max_length=50,
        null=False,
        blank=False
    )

    objetos = models.Manager()
    def __str__(self):
        return f'ID:{self.id} - {self.nome}'

class Produto(models.Model):
    nome_produto = models.CharField(
        max_length=50,
        null=False,
        blank=False
    )
    descricao = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )
    preco = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        null=False,
        blank=False
    )
    objetos = models.Manager()
    def __str__(self):
        return f'ID:{self.id} - {self.nome_produto}'

class Venda(models.Model):
    cliente = models.ForeignKey(
        'Cliente',
        on_delete=models.CASCADE
    )

    produto = models.ForeignKey(
        'Produto',
        on_delete=models.CASCADE
    )

    data_hora = models.DateTimeField(
        auto_now_add=True
    )
    objetos = models.Manager()


class Fila(models.Model):
    venda = models.ForeignKey(
        'Venda',
        on_delete=models.CASCADE
    )
    objetos = models.Manager()

padaria/forms.py
from django import forms

from padaria.models import Cliente, Produto, Venda


# class ClienteForm(forms.Form):
#     nome = forms.CharField(max_length=30, required=True)
#     sobrenome = forms.CharField(max_length=50, required=True)
#     cpf = forms.CharField(max_length=14, required=True)
#     email = forms.EmailField(max_length=50, required=True)
#     pass

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = [
            'nome',
            'sobrenome',
            'cpf',
            'email'
        ]
    pass


class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = [
            'nome_produto',
            'descricao',
            'preco'
        ]
        labels = {
            'nome_produto': 'Produto',
            'descricao': 'Descrição',
            'preco': 'Preço'
        }

    pass

class VendaForm(forms.ModelForm):
    class Meta:
        model = Venda
        fields = [
            'cliente',
            'produto'
        ]
        labels = {
            'cliente': 'Cliente',
            'produto': 'Produto'
        }

padaria/views.py
from django.contrib.messages import success
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView, CreateView, UpdateView

from padaria.forms import ClienteForm, ProdutoForm
from padaria.models import Cliente, Produto, Venda, Fila


# Create your views here.
def home(requisicao: HttpRequest):
    if requisicao.method == 'GET':
        return render(requisicao, template_name='padaria/base.html')


def cria_cliente(requisicao: HttpRequest):
    if requisicao.method == 'GET':
        form = ClienteForm()
        return render(requisicao, template_name='padaria/clientes/novo.html', context={'form': form})
    elif requisicao.method == 'POST':
        form = ClienteForm(requisicao.POST)
        if form.is_valid():
            cliente = Cliente(**form.cleaned_data)
            cliente.save()
            return HttpResponseRedirect(redirect_to='/')
        pass


def cria_produto(requisicao: HttpRequest):
    if requisicao.method == 'GET':
        form = ProdutoForm()
        return render(requisicao, template_name='padaria/produtos/novoProduto.html', context={'form': form})
    elif requisicao.method == 'POST':
        form = ProdutoForm(requisicao.POST)
        if form.is_valid():
            produto = Produto(**form.cleaned_data)
            produto.save()
            return HttpResponseRedirect(redirect_to='/')
        else:
            return render(requisicao, template_name='padaria/produtos/parametro_invalido.html', context={'form': form})
        pass


def lista_clientes(requisicao: HttpRequest):
    if requisicao.method == 'GET':
        clientes = Cliente.objetos.all()
        return render(requisicao, template_name='padaria/clientes/lista.html', context={'clientes': clientes})
    pass


def lista_produtos(requisicao: HttpRequest):
    if requisicao.method == 'GET':
        produtos = Produto.objetos.all()
        return render(requisicao, template_name='padaria/produtos/lista.html', context={'produtos': produtos})
    pass


def detalhe_produto(requisicao: HttpRequest, pk: int):
    if requisicao.method == 'GET':
        try:
            produto = Produto.objetos.get(pk=pk)
        except Produto.DoesNotExist:
            produto = None

        return render(requisicao,template_name='padaria/produtos/detalhe.html', context={'produto': produto})


def atualiza_produto(requisicao: HttpRequest, pk: int):
    if requisicao.method == 'GET':
        produto = Produto.objetos.get(pk=pk)
        form = ProdutoForm(instance=produto)
        return render(requisicao, template_name='padaria/produtos/atualiza.html', context={'form': form})
    elif requisicao.method == 'POST':
        produto = Produto.objetos.get(pk=pk)
        form = ProdutoForm(requisicao.POST, instance=produto)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(redirect_to=f'/produtos/detalhe/{pk}')

class RemoveProdutoView(DeleteView):
    model = Produto
    template_name = 'padaria/produtos/remove.html'
    context_object_name = 'produto'
    success_url = reverse_lazy('padaria:lista_produtos')

    def get_object(self, queryset=None):
        try:
            return super().get_object(queryset)
        except Http404:
            return None

class VendaListView(ListView):
    model = Venda
    template_name = 'padaria/vendas/lista.html'
    context_object_name = 'vendas'
    success_url = reverse_lazy('padaria:lista_vendas')

class VendaCreateView(CreateView):
    model = Venda
    template_name = 'padaria/vendas/novo.html'
    fields = ['cliente', 'produto']
    success_url = reverse_lazy('padaria:lista_vendas')


class AtualizaCreateView(UpdateView):
    model = Venda
    template_name = 'padaria/vendas/atualiza.html'
    fields = '__all__'
    context_object_name = 'venda'
    success_url = reverse_lazy('padaria:lista_vendas')

    def get_object(self, queryset=None):
        try:
            return super().get_object(queryset)
        except Http404:
            return None


class RemoveVendaView(DeleteView):
    model = Venda
    template_name = 'padaria/vendas/remove.html'
    fields = '__all__'
    context_object_name = 'venda'
    success_url = reverse_lazy('padaria:lista_vendas')

    def get_object(self, queryset=None):
        try:
            return super().get_object(queryset)
        except Http404:
            return None

padaria/templates/padaria/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Padaria da Susi</title>
</head>
<body>
    <header style="background-color: rgb(240, 204, 160);">
        <figure style="text-align: center;">
            {% load static %}
            <img src="{% static 'raiz/pao.jpg' %}" alt="Pão profissional com gosto caseiro" width="50%">
        </figure>
        <h1 style="text-align: center;">Bem vindo a Padaria da Susi!</h1>
        <nav style="text-align: center; background-color: bisque">
            <a href="/clientes/novo">Novo Cliente</a>
            <a href="/clientes/">Listar Clientes</a>
            <a href="/produtos/novoProduto">Novo Produto</a>
            <a href="/produtos/">Listar Produtos</a>
            <a href="/vendas/novo">Faça seu pedido!</a>
            <a href="/vendas/">Fila de atendimento</a>
        </nav>
    </header>
    <main>
        <article style="text-align: center;">
            <br>
            {% block content %}

            {% endblock %}
        </article>
        <br>
    </main>
    <footer style="background-color: rgb(240, 204, 160);">Todos os direitos reservados. CNPJ 098.009.099/0001-23</footer>

</body>
</html>

padaria/templates/padaria/clientes/lista.html
{% extends "padaria/base.html" %}
{% block content %}
<table align="center">
    <thead>
    <tr>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>CPF</th>
        <th>E-mail</th>

    </tr>
    </thead>
    <tbody>
        {% for cliente in clientes %}
            <tr>
                <td>{{ cliente.nome }}</td>
                <td>{{ cliente.sobrenome }}</td>
                <td>{{ cliente.cpf }}</td>
                <td>{{ cliente.email }}</td>

            </tr>
        {% endfor %}
    </tbody>

</table>

{% endblock content %}

padaria/templates/padaria/clientes/novo.html
{% extends "padaria/base.html" %}
{% block content %}
<h1>Formulário de Inclusão de Cliente</h1>

<form method="post">
    {% csrf_token %}

    {{ form }}

    <button type="submit">Cadastrar</button>

</form>
{% endblock content %}

padaria/templates/padaria/produtos/atualiza.html
{% extends "padaria/base.html" %}
{% block content %}
    <h1>Atualização de Produto</h1>
    <form method="post">
    {% csrf_token %}

    {{ form }}

    <button type="submit">Atualizar</button>

</form>
{% endblock content %}

padaria/templates/padaria/produtos/detalhe.html
{% extends "padaria/base.html" %}
{% block content %}
    <h1> Detalhe do Produto {{ produto.nome_produto }}</h1>
    {% if produto %}
        <ul>
            <li>Nome: {{ produto.nome_produto }}</li>
            <li>Descrição: {{ produto.descricao }}</li>
            <li>Preço: {{ produto.preco }}</li>
        </ul>
    {% else %}
        <h1> Nenhum produto encontrado para esse identificador!!</h1>
    {% endif %}

{% endblock content %}

padaria/templates/padaria/produtos/lista.html
{% extends "padaria/base.html" %}
{% block content %}
<h1>Lista de Produtos</h1>
<table  align="center">
    <thead>
    <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Valor</th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
        {% for produto in produtos %}
            <tr>
                <td>{{ produto.nome_produto }}</td>
                <td>{{ produto.descricao }}</td>
                <td>{{ produto.preco }}</td>
                <td>
                    <a href="{% url 'padaria:produtos_atualiza' pk=produto.id %}">Atualizar</a>
                    <a href="{% url 'padaria:remove_produto' pk=produto.id %}">Remover</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>

</table>
{% endblock content %}

padaria/templates/padaria/produtos/novoProduto.html
{% extends "padaria/base.html" %}
{% block content %}
<h1>Formulário de Inclusão de Produtos</h1>

<form method="post">
    {% csrf_token %}

    {{ form }}

    <button type="submit">Cadastrar</button>

</form>
{% endblock content %}

padaria/templates/padaria/produtos/parametro_invalido.html
{% extends "padaria/base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}

    {{ form }}

    <button type="submit">Cadastrar</button>

</form>
{% endblock content %}

padaria/templates/padaria/produtos/remove.html
{% extends "padaria/base.html" %}
{% block content %}


    {% if produto %}
        <h1>Confirma remoção do Produto: {{ produto.nome_produto }}</h1>
        <form method="post">
            {% csrf_token%}

            <p>Você confirma a remoção do produto: {{ produto.id }} - {{ produto.nome_produto }}</p>
            <button type="submit">Confirmar Remoção</button>
        </form>
    {% else %}
        <h1>Produto com esse ID não encontrado!</h1>
    {% endif %}
{% endblock content %}

padaria/templates/padaria/vendas/atualiza.html
{% extends "padaria/base.html" %}
{% block content %}
 <h1>Atualização de Venda</h1>
    <form method="post">
    {% csrf_token %}

    {{ form }}

    <button type="submit">Atualizar</button>

</form>
{% endblock content %}

padaria/templates/padaria/vendas/lista.html
{% extends "padaria/base.html" %}
{% block content %}
<h1>Fila de Atendimento</h1>
<table  align="center">
    <thead>
    <tr>
        <th>ID</th>
        <th>Cliente</th>
        <th>Produto</th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
        {% for venda in vendas %}
            <tr>
                <td>{{ venda.id }}</td>
                <td>{{ venda.cliente.nome }}</td>
                <td>{{ venda.produto.nome_produto }}</td>
                <td>{{ venda.data_hora }}</td>
                <td>
                    <a href="{% url 'padaria:atualiza_venda' pk=venda.id %}">Atualizar</a>
                    <a href="{% url 'padaria:remove_venda' pk=venda.id %}">Remover</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>

</table>
{% endblock content %}

padaria/templates/padaria/vendas/novo.html
{% extends "padaria/base.html" %}
{% block content %}
<h1>Formulário de Inclusão de Venda</h1>

<form method="post">
    {% csrf_token %}

    {{ form }}

    <button type="submit">Cadastrar</button>

</form>
{% endblock content %}

padaria/templates/padaria/vendas/remove.html
{% extends "padaria/base.html" %}
{% block content %}
    {% if venda %}
        <h1>Confirma remoção dA Venda: {{ venda.id }} - {{ venda.cliente.nome }} - {{ venda.produto.nome_produto }}</h1>
        <form method="post">
            {% csrf_token%}

            <p>Você confirma a remoção do produto: {{ venda.id }} - {{ venda.cliente.nome }} - {{ venda.produto.nome_produto }}</p>
            <button type="submit">Confirmar Remoção</button>
        </form>
    {% else %}
        <h1>Venda com esse ID não encontrada!</h1>
    {% endif %}
{% endblock content %}